### ISSUE TITLE
Issue in html indentation styling

### ISSUE THREAD

**Issue by joskalenda** [tariktesfa/My-portfolio#5]
### Everything is well designed so far, except the HTML inner elements which are not well indented in a good styling
See this image and check the rest, there must be an indentation of 2 spaces, not 4.

![Screenshot from 2021-12-02 10-01-38](https://user-images.githubusercontent.com/77843050/144382311-532503b2-c800-4aed-9f51-0f096468fc26.png)

**Comment by tariktesfa** [comment]
Fixed the issue.
