### ISSUE TITLE
Responsiveness.

### ISSUE THREAD

**Issue by muneebulrehman** [tariktesfa/My-portfolio#8]
Responsiveness of the cards in the work section in mobile view breaks. The button is going out of the flow of the card. Also, the some of the text is wrapping around itself.

**Comment by guerreiropedr0** [comment]
I would like to point out a few things about your code, first of all, your code is great but can be improved:
- The contact me section should be flexbox;
- You could make the contact me section centered as well!
- In the mobile version, the buttons from the work's template are coming out of the container;
- In the README.md file, the live demo could have a better description! 😃

**Comment by ismailakinkunmi** [comment]
I will suggest you use width 50% for your form container, this will make your mobile and desktop version have almost the same look.
